version: "2"
checks:
  argument-count:
    enabled: true
    config:
      threshold: 5
  complex-logic:
    enabled: true
    config:
      threshold: 50
  file-lines:
    enabled: true
    config:
      threshold: 500
  method-complexity:
    enabled: true
    config:
      threshold: 20
  method-count:
    enabled: true
    config:
      threshold: 50
  method-lines:
    enabled: true
    config:
      threshold: 50
  nested-control-flow:
    enabled: true
    config:
      threshold: 10
  return-statements:
    enabled: true
    config:
      threshold: 10
  similar-code:
    enabled: false
  identical-code:
    enabled: false
exclude_patterns:
- "assets/"
- "android/"
- "ios/"
- "node_modules/"
- "**/node_modules/"
- "storybook/"
